#include rendering_helper.script
#include math_helper.script

// Setting variables
var pixelPerUnit = 100

// List where we store all of our Triangles
var trigs = lnew()

var trianglesPerCircle = 25

for var i = 0; i < 6*trianglesPerCircle; it(i) {
    trigs.add(0)
}

// Acceleration
var g = 9.81
// Time scale
var timeScale = 0.002
var friction = 0.995
var bounce = 0.7

// Units to Pixel
var pixelPerUnit = 50

// Game width and height
var width = 20
var height = 20

// Camera stuff (upper left corner)
var cameraX = 1
var cameraY = 1
var cameraSpeed = 0.2

// Amount of balls
var ballAmount = 10

// Balls and velocities
var balls = lnew()
var vels = lnew()

for var i = 0; i < ballAmount; it(i) {
    balls.add(i*0.8+2)
    balls.add(5*random())

    vels.add((random()-0.5)*0.2)
    vels.add((random()-0.5)*0.2)
}

#macro updateGame() {
    for var __ball = 0; __ball < ballAmount; it(__ball) {
        vels[__ball*2+1] = vels[__ball*2+1] + g * timeScale

        #updateAxis(balls[__ball*2],   vels[__ball*2],   1, width - 1)
        #updateAxis(balls[__ball*2+1], vels[__ball*2+1], 1, height - 1)
    }
}

#macro updateAxis(val, vel, min, max) {
    $val = $vel + $val
    if ($val < $min) {
        $val = $min
        $vel = -$vel * bounce
    }
    if ($val > $max) {
        $val = $max
        $vel = -$vel * bounce
    }

    $vel = $vel * friction
}

dStart()
#fillScreen(0, 0, 0, 255)
dEnd()

for ;; {
    #updateGame()
    #drawGame()
    sleep(16)
}

#macro drawGame() {
    dStart()
    #dealWithInput()

    // Clear screen
    #fillScreen(0, 0, 0, 255)

    #fill(cameraX*pixelPerUnit, cameraY*pixelPerUnit, width*pixelPerUnit, height*pixelPerUnit, 30, 30, 30, 255)

    for var ball = 0; ball < ballAmount; it(ball) {
        var an = atan2(vels[ball*2+1], vels[ball*2])
        var velLength = sqrt(vels[ball*2+1]*vels[ball*2+1]+vels[ball*2]*vels[ball*2])
        var hFactor = 1 / (velLength*0.4+1)
        var wFactor = 1 / hFactor
        var c = 0
        #min(velLength / 0.8, 1, c)

        #drawBall(pixelPerUnit*wFactor, pixelPerUnit*hFactor, (balls[ball*2]+cameraX)*pixelPerUnit, (balls[ball*2+1]+cameraY)*pixelPerUnit, an, c)
    }

    dEnd()
}

#macro dealWithInput() {
    if (isPressed(87)) { // w
        cameraY = cameraY + cameraSpeed
    }
    if (isPressed(83)) { // s
        cameraY = cameraY - cameraSpeed
    }
    if (isPressed(65)) { // a
        cameraX = cameraX + cameraSpeed
    }
    if (isPressed(68)) { // d
        cameraX = cameraX - cameraSpeed
    }

    if isMousePressed(0) {
        #applyMouse(100, 1)
    }
    if isMousePressed(1) {
        #applyMouse(-30, 0.5)
    }
}

#macro applyMouse(scalar, scalarDist) {
    for var __i = 0; __i < ballAmount; it(__i) {
        var __dist = 0
        #distance(balls[__i*2], balls[__i*2+1], mouseX()/pixelPerUnit, mouseY()/pixelPerUnit, __dist)
        __dist = __dist * $scalarDist

        #clamp(__dist, 0.5, 10000)

        var __dirX = balls[__i*2] - mouseX()/pixelPerUnit
        var __dirY = balls[__i*2+1] - mouseY()/pixelPerUnit

        __dirX = __dirX / __dist ^ 2
        __dirY = __dirY / __dist ^ 2

        vels[__i*2] = vels[__i*2] + __dirX * timeScale * $scalar
        vels[__i*2+1] = vels[__i*2+1] + __dirY * timeScale * $scalar
    }
}

#macro drawBall(xSize, ySize, xCenter, yCenter, angle, colorFactor) {
    // Put triangle data into the list
    #setToRegularPolygonRotated(trigs, 0, trianglesPerCircle, $xSize, $ySize, $xCenter, $yCenter, $angle)

    var __colorFac = floor(200 * $colorFactor + 33 * (1-$colorFactor))
    setColor(__colorFac, __colorFac, __colorFac, 255)

    trigs.drawTriangles()
}